from django.urls import path
from . import views
urlpatterns = [
    path('login', views.signin, name='login'),
    path('logout', views.signout, name='signout'),
    path('profile', views.profile, name='profile'),
    path('change-password', views.change_password, name='change-password'),
    path('', views.dashboard, name="dashboard"),
    path('all-posts', views.posts_listing, name="all-posts"),
    path('write-post', views.write_blog_post, name="write-post"),
    path('category-and-tags', views.category_tags, name="category-and-tags"),
    path('add-category', views.add_category, name="add-category"),
    path('add-tag', views.add_tag, name="add-category"),
    path('get-category-data/<int:id>', views.get_category, name="get-category"),
    path('get-tag-data/<int:id>', views.get_tag, name="get-tag"),
    path('update-category', views.update_category, name="update-category"),
    path('update-tag', views.update_tag, name="update-tag"),
    path('delete-tag/<int:id>', views.delete_tag, name="update-tag"),
    path('delete-category/<int:id>', views.delete_category, name="delete-tag"),
    path('get-all-tags', views.get_all_tags, name="get-all-tags"),
    path('save-new-post', views.add_post, name="save-new-post"),
    path('change-publish-status/<int:id>', views.change_publish_status, name="change-publish-status"),
    path('update-post/<int:id>', views.get_post_data, name="update-post"),
    path('delete-post/<int:id>', views.delete_post, name="delete-post"),
    path('check-slug/<str:slug>', views.is_slug_available, name="check-slug"),
    path('get-post-tags/<int:post_id>', views.get_post_tags, name="get-post-tags"),
    path('change-featured-status/<int:id>', views.change_featured_category_status,
        name="change-featured-category-status"),
]
